apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanbaiki-web
  labels:
    app: hanbaiki-web
spec:
  selector:
    matchLabels:
      app: hanbaiki-web
  template:
    metadata:
      labels:
        app: hanbaiki-web
    spec:
      containers:
        - name: hanbaiki-web
          image: defn/hanbaiki:web
          ports:
            - name: hanbaiki-web
              containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanbaiki-api
  labels:
    app: hanbaiki-api
spec:
  selector:
    matchLabels:
      app: hanbaiki-api
  template:
    metadata:
      labels:
        app: hanbaiki-api
    spec:
      containers:
        - name: hanbaiki-api
          image: defn/hanbaiki:api
          ports:
            - name: hanbaiki-api
              containerPort: 8000
