apiVersion: v1
kind: Service
metadata:
  name: hanbaiki
  labels:
    app: hanbaiki
spec:
  ports:
    - name: hanbaiki
      port: 3000
      protocol: TCP
      targetPort: hanbaiki
  selector:
    app: hanbaiki
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hanbaiki-dist
  labels:
    app: hanbaiki-dist
spec:
  ports:
    - name: hanbaiki-dist
      port: 80
      protocol: TCP
      targetPort: hanbaiki-dist
  selector:
    app: hanbaiki-dist
  type: ClusterIP
